version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: aivacol_sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=S3nh4_Str0ng_2026!
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  redis:
    image: redis:7-alpine
    container_name: aivacol_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: aivacol_backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_HOST=sqlserver
      - DB_PORT=1433
      - DB_USERNAME=sa
      - DB_PASSWORD=S3nh4_Str0ng_2026!
      - DB_DATABASE=master
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=AivacolSecretToken2026
      - JWT_EXPIRES_IN=1d
    depends_on:
      - sqlserver
      - redis

volumes:
  mssql_data:
  redis_data: